version: "3.8"
    
services:
  db:
    image: postgres:11.6
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  web:
    command: >
      bash -c "while ! nc -w 1 -z db 5432;
              do sleep 0.1;
              done;
              python manage.py migrate;
              python manage.py runserver 0.0.0.0:8000"
    build: .
    image: symposium
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db